export const categories = {
  subjects: [
    "Time tracking",
    "Project management",
    "Customer relationship management (CRM)",
    "Email marketing",
    "Social media management",
    "Inventory management",
    "Accounting and bookkeeping",
    "Employee scheduling",
    "Task automation",
    "Website analytics",
    "Content creation",
    "Learning management",
    "Virtual event hosting",
    "Customer support ticketing",
    "Expense tracking",
    "Team collaboration",
    "Video conferencing",
    "Password management",
    "Data visualization",
    "Pet care management",
    "Freelance project tracking",
    "Sustainable living tracking",
    "Niche hobby marketplace",
    "Mental health journaling",
    "Personalized meal planning",
    "Local event discovery",
    "Micro-learning platform",
    "Virtual interior design",
    "Fitness progress visualization",
    "Language exchange matching",
    "Collaborative songwriting",
    "Volunteer opportunity finding",
    "Subscription box curation",
    "Personal finance coaching",
    "Personal habit tracking",
    "Digital asset management",
    "Remote team building",
    "Influencer collaboration",
    "Podcast production and hosting",
    "Gamified productivity",
    "Cryptocurrency portfolio tracking",
    "Mindfulness and meditation guidance",
    "Personal carbon footprint calculation",
    "Skill-sharing marketplace",
    "Virtual coworking space",
    "Digital estate planning",
    "AI-powered writing coaching",
    "No-code development platform",
    "Subscription management",
    "Micro-SaaS builder",
    "Niche job board",
    "Personal brand management",
    "Automated lead generation",
    "AI-powered market research",
    "Crowdfunding campaign management",
    "Startup valuation calculator",
    "Business plan generator",
    "Growth hacking toolkit",
    "Pitch deck creator",
    "Investor matching platform",
    "Startup ecosystem mapper"
  ],
  forms: [
    "web application",
    "mobile app",
    "browser extension",
    "desktop software",
    "API service",
    "AI-powered assistant",
    "chatbot",
    "Chrome extension",
    "Slack integration",
    "WordPress plugin",
    "Shopify app",
    "Zapier integration",
    "voice-activated tool",
    "progressive web app (PWA)",
    "command-line interface (CLI)",
    "email-based service",
    "SMS-based service",
    "visual no-code platform",
    "IoT device companion app",
    "smartwatch app",
    "social media plugin",
    "Alexa skill",
    "Google Home action",
    "Telegram bot",
    "WhatsApp business tool",
    "Notion template",
    "Airtable base",
    "Figma plugin",
    "Trello power-up",
    "Salesforce app",
    "Zoom integration",
    "Discord bot",
    "Twitch extension",
    "Apple Watch complication",
    "Google Sheets add-on",
    "Microsoft Teams app",
    "Siri shortcut",
    "QR code-based service",
    "NFC tag integration",
    "Raspberry Pi project",
    "3D printing companion app",
    "podcast player integration",
    "smart home integration",
    "gamification platform",
    "biometric authentication tool",
    "SaaS platform",
    "low-code development tool",
    "browser-based IDE",
    "AI model marketplace",
    "no-code database",
    "serverless function",
    "WebAssembly module",
    "GitHub Action",
    "Docker container"
  ],
  targetAudiences: [
    "small business owners",
    "freelancers",
    "remote teams",
    "e-commerce businesses",
    "digital marketers",
    "startups",
    "non-profit organizations",
    "educational institutions",
    "healthcare providers",
    "real estate agents",
    "restaurants and hospitality businesses",
    "fitness professionals",
    "creative agencies",
    "software developers",
    "legal professionals",
    "financial advisors",
    "event planners",
    "podcasters and content creators",
    "manufacturers",
    "consultants and coaches",
    "digital nomads",
    "new parents",
    "retirees",
    "college students",
    "chronic illness patients",
    "aspiring artists",
    "home gardeners",
    "adventure travelers",
    "eco-conscious consumers",
    "busy professionals",
    "LGBTQ+ community members",
    "neurodivergent individuals",
    "minimalists",
    "craft beer enthusiasts",
    "pet owners",
    "gamers and streamers",
    "foodies and amateur chefs",
    "car enthusiasts",
    "book lovers and writers",
    "genealogy researchers",
    "outdoor enthusiasts",
    "fashion and beauty influencers",
    "DIY home improvers",
    "collectors",
    "language learners",
    "sustainable fashion advocates",
    "urban farmers",
    "indie game developers",
    "vintage and antique enthusiasts",
    "amateur astronomers",
    "solopreneurs",
    "angel investors",
    "venture capitalists",
    "startup accelerators",
    "tech bootcamp graduates",
    "serial entrepreneurs",
    "side hustlers",
    "gig economy workers",
    "product managers",
    "growth hackers",
    "no-code enthusiasts",
    "indie hackers",
    "SaaS founders",
    "blockchain developers",
    "AI researchers"
  ]
};
